<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GameManaged Condition="'$(GameManaged)' == ''">$(MSBuildProjectDirectory)/../../../../../../App/Steam/steamapps/common/RimWorld/RimWorldWin64_Data/Managed</GameManaged>
    <HarmonyPath Condition="'$(HarmonyPath)' == ''">$(MSBuildProjectDirectory)/../../../../../../App/Steam/steamapps/workshop/content/294100/2009463077/Current/Assemblies/0Harmony.dll</HarmonyPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameManaged)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManaged)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(HarmonyPath)</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
